# Use an official Node.js LTS version as a parent image
FROM node:14.17.4

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json ./
RUN npm install

# Copy all frontend files to the container
COPY . .

# Build the frontend
RUN npm run build

# Expose the port on which the frontend will run
EXPOSE 3000

# Start the frontend server
CMD ["npm", "start"]
